version: '3'

services:
  cat-app:
    image: 'sachinpgade/docker-apps:cat-latest'
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
